version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-app
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    restart: always
    networks:
      - go-server

  postgres:
    image: postgres:17.5-alpine3.22
    container_name: go-postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - go-server

  redis:
    image: redis:8.0.2-alpine3.21
    container_name: go-redis
    ports:
      - 6379:6379
    restart: always
    networks:
      - go-server

networks:
  go-server:
    driver: bridge
