version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: go-app
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    volumes:
      - ./:/app
    depends_on:
      - postgres
      - redis
    restart: always
    networks:
      - go-server